-- Add ActivityType enum values
ALTER TYPE "ActivityType" ADD VALUE 'TASK_CREATED' BEFORE 'TASK_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_MOVED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_DELETED';
ALTER TYPE "ActivityType" ADD VALUE 'COMMENT_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'BOARD_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'START_DATE_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'START_DATE_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'START_DATE_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE 'DUE_DATE_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'DUE_DATE_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'DUE_DATE_REMOVED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_ASSIGNED';
ALTER TYPE "ActivityType" ADD VALUE 'TASK_UNASSIGNED';
ALTER TYPE "ActivityType" ADD VALUE 'MEETING_NOTE_ADDED';
ALTER TYPE "ActivityType" ADD VALUE 'QUICK_NOTE_ADDED';
