-- Seed demo risks data for risk management system
-- This data populates the risks table with diverse samples for visualization testing

INSERT INTO public.risks (
  title,
  description,
  probability,
  impact,
  status,
  mitigation_plan,
  risk_owner,
  risk_category,
  likelihood_score,
  impact_score,
  mitigation_status,
  key_risk_indicator,
  next_review_date,
  residual_risk_score
) VALUES
-- Critical Risks (High Likelihood × High Impact)
(
  'Critical System Outage',
  'Database server failure could cause complete system unavailability',
  'High',
  'High',
  'Open',
  'Implement redundant database servers and automated failover mechanisms',
  'John Smith',
  'Operational',
  5,
  5,
  'In Progress',
  'System uptime percentage, failure response time',
  NOW() + INTERVAL '14 days',
  9
),
(
  'Security Breach Risk',
  'Potential data theft or unauthorized access to sensitive customer information',
  'High',
  'High',
  'Open',
  'Enhanced encryption, multi-factor authentication, regular security audits',
  'Sarah Johnson',
  'Compliance',
  5,
  4,
  'In Progress',
  'Failed login attempts, unauthorized data access attempts',
  NOW() + INTERVAL '7 days',
  6
),

-- High Risks (Medium-High Likelihood × Medium-High Impact)
(
  'Key Personnel Departure',
  'Loss of critical team members could impact project delivery',
  'High',
  'Medium',
  'Open',
  'Knowledge documentation, cross-training program, retention incentives',
  'Michael Chen',
  'Operational',
  4,
  4,
  'Not Started',
  'Employee turnover rate, onboarding completion time',
  NOW() + INTERVAL '30 days',
  NULL
),
(
  'Budget Overrun',
  'Project costs may exceed allocated budget due to scope creep',
  'Medium',
  'High',
  'Open',
  'Strict change management process, monthly budget reviews',
  'Lisa Anderson',
  'Financial',
  3,
  5,
  'In Progress',
  'Actual vs budgeted costs, change request volume',
  NOW() + INTERVAL '10 days',
  8
),
(
  'Vendor Dependency',
  'Over-reliance on single third-party vendor creates risk',
  'High',
  'Medium',
  'Mitigated',
  'Identify alternative vendors, establish contingency plans',
  'Robert Davis',
  'Strategic',
  4,
  3,
  'Complete',
  'Vendor performance metrics, alternative vendor availability',
  NOW() + INTERVAL '60 days',
  3
),

-- Medium Risks
(
  'Delayed Deliverables',
  'Project milestones may be delayed due to resource constraints',
  'Medium',
  'Medium',
  'Open',
  'Additional resource allocation, priority adjustment',
  'Jessica White',
  'Operational',
  3,
  3,
  'On Hold',
  'Schedule variance, milestone completion percentage',
  NOW() + INTERVAL '20 days',
  5
),
(
  'Data Quality Issues',
  'Inconsistent or incomplete data affecting reporting accuracy',
  'Medium',
  'Medium',
  'Open',
  'Data validation rules, automated quality checks, regular audits',
  'James Martinez',
  'Operational',
  3,
  3,
  'Complete',
  'Data error rate, audit findings count',
  NOW() + INTERVAL '15 days',
  1
),
(
  'Regulatory Compliance Changes',
  'New regulations could require significant process changes',
  'Medium',
  'High',
  'Open',
  'Legal review, compliance assessment, documentation updates',
  'Emma Thompson',
  'Compliance',
  3,
  4,
  'On Hold',
  'Compliance audit findings, policy update frequency',
  NOW() + INTERVAL '45 days',
  8
),
(
  'Market Competition Increase',
  'New market entrants could reduce market share',
  'High',
  'Medium',
  'Open',
  'Product differentiation, customer retention program',
  'David Wilson',
  'Market',
  4,
  3,
  'In Progress',
  'Market share percentage, customer satisfaction score',
  NOW() + INTERVAL '90 days',
  5
),

-- Lower-Medium Risks
(
  'Infrastructure Scalability',
  'Current infrastructure may not support future growth',
  'Medium',
  'Low',
  'Open',
  'Capacity planning, gradual infrastructure upgrade',
  'Paul Garcia',
  'Operational',
  3,
  2,
  'In Progress',
  'System resource utilization, response time metrics',
  NOW() + INTERVAL '60 days',
  2
),
(
  'Documentation Gaps',
  'Incomplete documentation could impact knowledge transfer',
  'Low',
  'Medium',
  'Open',
  'Create documentation standards, allocate documentation time',
  'Michelle Brown',
  'Operational',
  2,
  3,
  'In Progress',
  'Documentation completeness score, onboarding time',
  NOW() + INTERVAL '30 days',
  2
),

-- Low Risks
(
  'Minor Process Inefficiencies',
  'Current processes could be optimized for better efficiency',
  'Low',
  'Low',
  'Open',
  'Process review and optimization initiative',
  'Tom Davis',
  'Operational',
  1,
  2,
  'Not Started',
  'Process cycle time, resource utilization rate',
  NOW() + INTERVAL '120 days',
  NULL
),
(
  'Communication Delays',
  'Inter-team communication could be improved',
  'Low',
  'Low',
  'Closed',
  'Implement collaboration tools, regular sync meetings',
  'Nina Rodriguez',
  'Operational',
  2,
  1,
  'Complete',
  'Meeting efficiency score, response time metrics',
  NOW() + INTERVAL '180 days',
  1
),

-- Additional diverse risks
(
  'Third-party Integration Failure',
  'API integration with partners could fail unexpectedly',
  'Medium',
  'High',
  'Open',
  'Enhanced error handling, fallback mechanisms, partner communication',
  'Alex Turner',
  'Operational',
  3,
  4,
  'In Progress',
  'API uptime percentage, integration error rate',
  NOW() + INTERVAL '25 days',
  7
),
(
  'Cybersecurity Threat',
  'Malware or ransomware attack could compromise systems',
  'Medium',
  'High',
  'Open',
  'Security patches, antivirus software, employee training',
  'Sarah Johnson',
  'Compliance',
  3,
  5,
  'In Progress',
  'Security vulnerability count, patch deployment time',
  NOW() + INTERVAL '8 days',
  9
),
(
  'Customer Satisfaction Decline',
  'Quality issues or service degradation could harm reputation',
  'Low',
  'High',
  'Open',
  'Quality assurance improvements, customer feedback program',
  'Lisa Anderson',
  'Market',
  2,
  4,
  'In Progress',
  'NPS score, customer satisfaction rating, churn rate',
  NOW() + INTERVAL '35 days',
  3
),
(
  'Competitive Product Launch',
  'Competitor releasing similar product could impact sales',
  'Medium',
  'Medium',
  'Open',
  'Feature roadmap acceleration, pricing strategy adjustment',
  'David Wilson',
  'Market',
  3,
  3,
  'Not Started',
  'Sales pipeline impact, competitive win rate',
  NOW() + INTERVAL '50 days',
  NULL
),
(
  'Resource Allocation Conflict',
  'Competing project priorities could lead to resource conflicts',
  'High',
  'Low',
  'Open',
  'Clear prioritization matrix, resource planning process',
  'Michael Chen',
  'Operational',
  4,
  2,
  'In Progress',
  'Resource utilization variance, project delay incidents',
  NOW() + INTERVAL '18 days',
  2
),
(
  'Technology Debt Accumulation',
  'Legacy code and technical debt could slow development',
  'Medium',
  'Medium',
  'Open',
  'Code refactoring sprints, architecture modernization',
  'James Martinez',
  'Operational',
  3,
  3,
  'Complete',
  'Code coverage percentage, defect density, development velocity',
  NOW() + INTERVAL '75 days',
  2
),
(
  'Network Security Vulnerability',
  'Unpatched network vulnerabilities could be exploited',
  'High',
  'High',
  'Mitigated',
  'Regular vulnerability scanning, prompt patching, network segmentation',
  'Emma Thompson',
  'Compliance',
  5,
  4,
  'Complete',
  'Vulnerability count, mean time to remediation',
  NOW() + INTERVAL '90 days',
  6
),
(
  'Storage Capacity Crisis',
  'Data storage may run out of capacity',
  'Low',
  'Medium',
  'Open',
  'Archive old data, implement compression, add storage',
  'Paul Garcia',
  'Operational',
  2,
  3,
  'On Hold',
  'Storage utilization percentage, available capacity',
  NOW() + INTERVAL '120 days',
  2
);
